# ansible-playbook -K playbook.yml -i hosts
---
- name: Setup workstation
  hosts: local
  roles:
  # set caps lock to escape: https://askubuntu.com/a/365701
  #     + Dropbox
  #     + set up obsidian with Dropbox
    - prelude
    - ghostty
    - rust
    - git
    - keyboard
    - fonts
    - starship
    - dotnet
    - python
    - github-cli
    - haskell
    - neovim
    - dropbox
    - obsidian
    - vscode
    - nodejs
    - docker
    - rocm
