---
- name: Download GHCup installer
  ansible.builtin.get_url:
    url: https://get-ghcup.haskell.org
    dest: /tmp/get-ghcup.sh
  register: ghcup_installer

- name: Install GHCup
  ansible.builtin.script:
    cmd: "{{ ghcup_installer.dest }}"
    creates: "{{ ansible_env.HOME }}/.ghcup"
  environment:
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
    BOOTSTRAP_HASKELL_ADJUST_BASHRC: "1"
    BOOTSTRAP_HASKELL_INSTALL_NO_STACK: "1"
    BOOTSTRAP_HASKELL_INSTALL_HLS: "1"

- name: Install latest Haskell tools via GHCup
  ansible.builtin.command:
    argv:
      - ghcup
      - install
      - "{{ item }}"
      - latest
  register: ghcup_install
  changed_when: "'installation successful' in ghcup_install.stdout"
  loop:
    - cabal
    - ghc
    - hls